spring:
  application:
    name: RPGPlace

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb # In-memory database
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true # Enable H2 Console
      path: /h2-console # URL to access the console

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Creates/updates the schema, preserving data.
    show-sql: true # Show SQL statements in the console
    open-in-view: false # Best practice: disable open-in-view to avoid performance issues.
    properties:
      hibernate:
        format_sql: true # Format the SQL shown in the console

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.security: TRACE
    org.springframework.messaging: TRACE
