server:
  port: ${PORT:8080}

spring:
  application:
    name: RPGPlace

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl=true&sslmode=require&prepareThreshold=0
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Creates/updates the schema, preserving data.
    show-sql: true # Show SQL statements in the console
    open-in-view: false # Best practice: disable open-in-view to avoid performance issues.
    properties:
      hibernate:
        format_sql: true # Format the SQL shown in the console

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.security: TRACE
    org.springframework.messaging: TRACE